<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
 $meige_unique_general = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_general');
 $headerConfig = $meige_unique_general['header'];
 $siteLayout = $meige_unique_general['layout'];
 
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php if ($siteLayout['sitelayout'] == 1) : ?>
<div class="container_12 boxed-site">
<?php endif; ?>
	<?php echo $this->getChildHtml('after_body_start') ?>
	<?php echo $this->getChildHtml('global_notices') ?>
	<?php echo $this->getChildHtml('header') ?>
	<div class="content-wrapper">
		<div class="container_12">
			<div class="main-container col1-layout">
				<div class="grid_12 col-main">
					<?php 
						if($headerConfig['headertype'] == 1 && (Mage::getSingleton('cms/page')->getIdentifier() != 'home' && Mage::app()->getFrontController()->getRequest()->getRouteName() != 'cms')) {
							if($this->getChildHtml('breadcrumbs') || ($this->getLayout()->createBlock('cms/block')->setBlockId('unique_social_likes')->toHtml())) :
					?>
						<div class="breadcrumbs-wrapper type-2">
							<?php echo $this->getChildHtml('breadcrumbs') ?>
							<?php if ($this->getLayout()->createBlock('cms/block')->setBlockId('unique_social_likes')->toHtml()) :?>
								<div class="social-likes"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('unique_social_likes')->toHtml(); ?></div>
							<?php endif; ?>
						</div>
					<?php 
							endif;
						} 
					?>
					<?php echo $this->getChildHtml('global_messages') ?>
					<?php echo $this->getChildHtml('content') ?>
				</div>
				<div class="clear"></div>
			</div>    
		</div>
	</div>
	<?php echo $this->getChildHtml('footer') ?>
	<?php echo $this->getChildHtml('global_cookie_notice') ?>
	<?php echo $this->getChildHtml('before_body_end') ?>
	<?php echo $this->getAbsoluteFooter() ?>
<?php if ($siteLayout['sitelayout'] == 1) : ?>
</div>
<?php endif; ?>
</body>
</html>