<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
$meigee_unique_general = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_general');
$footer_status = $meigee_unique_general['footer']['footer_status'];
$footer_static = $meigee_unique_general['footer']['footer_static'];
?>
<footer id="footer"<?php if($footer_status == 0){echo ' class="original"';}?>>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-61922102-1', 'auto');
	  ga('send', 'pageview');

	</script>


	<?php if($footer_status == 1): ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($footer_static)->toHtml() ?>
	<?php else: ?>
		<div class="container_12">
			<div class="grid_12">
				<div class="footer-links">
					<?php echo $this->getChildHtml('cms_footer_links') ?>
					<?php echo $this->getChildHtml('footer_links') ?>
				</div>
				<?php if ($static_html = $this->getChildHtml('unique_original_footer_logo')): ?>
					<?php echo $static_html; ?>
				<?php endif; ?>
				<address><?php echo $this->getCopyright() ?></address>
				<?php echo $this->getChildHtml('store_switcher') ?>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>
	<?php endif; ?>
</footer>
