<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><i class="icon-user"></i><?php echo $this->__(Mage::getSingleton('customer/session')->getCustomer()->getFirstname ()).' '.$this->__(Mage::getSingleton('customer/session')->getCustomer()->getLastname ()); ?></span></strong>
    </div>
    <div class="block-content">
		<ul>	
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); 
		/* ESPL SAN 20150311 0555PM START */
		 unset($_links['billing_agreements']); /* Billing Agreements */
		 unset($_links['recurring_profiles']); /* Recurring Profiles */
		 unset($_links['tags']); /* My Tags */
		 unset($_links['OAuth Customer Tokens']); /* My Applications */
		 unset($_links['downloadable_products']); /* My Downloadable Products */
		/* ESPL SAN 20150311 0555PM END */
	    ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><i class="fa fa-caret-right"></i><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><i class="fa fa-caret-right"></i><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
