<?php 
/*****/
$meigee_unique_headerslider = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_headerslider');
$headerSliderConfig = $meigee_unique_headerslider['coin'];
/*****/

$show = 0;
if ($headerSliderConfig ['enabled'] && $headerSliderConfig ['slides']):

  /**/
  if ($headerSliderConfig['onlyhome']):
	if(Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms'):
      $show = 1;
    endif;
  else:
    $show = 1;
  endif;
  /**/

if ($show): 
	if ($headerSliderConfig['slidertype'] == 0) {
		$headerSlidesList = explode(",", str_replace(" ", "", $headerSliderConfig ['slides']));
	} else if ($headerSliderConfig['slidertype'] == 1) {
		$headerSlidesList = explode(",", str_replace(" ", "", $headerSliderConfig ['boxedslides']));
	} else if ($headerSliderConfig['slidertype'] == 2) {
		$headerSlidesList = explode(",", str_replace(" ", "", $headerSliderConfig ['boxed_slides_width_banners']));
		$sliderBanners = $headerSliderConfig['sliderbanners'];
	} else if ($headerSliderConfig['slidertype'] == 3) {
		$headerSlidesList = explode(",", str_replace(" ", "", $headerSliderConfig ['header2_boxedslides']));
	} else if ($headerSliderConfig['slidertype'] == 4) {
		$headerSlidesList = explode(",", str_replace(" ", "", $headerSliderConfig ['header2_boxed_slides_width_banners']));
		$sliderBanners = $headerSliderConfig['header2_sliderbanners'];
	}
?>

<?php if($headerSliderConfig['slidertype'] == 0): ?>
<div class="header-slider-holder<?php if($headerSliderConfig['preloader'] == 1): ?> loading<?php endif; ?>">
		<?php if($headerSliderConfig['preloader'] == 1): ?><div class="loader"></div><?php endif; ?>
<?php endif; ?>
	<?php if($headerSliderConfig['slidertype'] == 1) : ?>
		<div class="grid_9 alpha omega slider-without-banners">
			<div class="header-slider-holder<?php if($headerSliderConfig['preloader'] == 1): ?> loading<?php endif; ?>">
		<?php if($headerSliderConfig['preloader'] == 1): ?><div class="loader"></div><?php endif; ?>
	<?php endif; ?>
	<?php if($headerSliderConfig['slidertype'] == 2) : ?>
		<div class="grid_6 alpha omega slider-with-banners">
			<div class="header-slider-holder<?php if($headerSliderConfig['preloader'] == 1): ?> loading<?php endif; ?>">
		<?php if($headerSliderConfig['preloader'] == 1): ?><div class="loader"></div><?php endif; ?>
	<?php endif; ?>
	<?php if($headerSliderConfig['slidertype'] == 3) : ?>
		<div class="grid_12 alpha omega slider-without-banners">
			<div class="header-slider-holder<?php if($headerSliderConfig['preloader'] == 1): ?> loading<?php endif; ?>">
		<?php if($headerSliderConfig['preloader'] == 1): ?><div class="loader"></div><?php endif; ?>
	<?php endif; ?>
	<?php if($headerSliderConfig['slidertype'] == 4) : ?>
		<div class="grid_8 alpha omega slider-with-banners">
			<div class="header-slider-holder<?php if($headerSliderConfig['preloader'] == 1): ?> loading<?php endif; ?>">
				<?php if($headerSliderConfig['preloader'] == 1): ?><div class="loader"></div><?php endif; ?>
	<?php endif; ?>
			<div class="header-slider-container<?php if($headerSliderConfig['slidertype'] == 0){echo ' wide-slider';} else {echo ' boxed-slider';} ?>">
				<div class="container">
					<div class="iosSlider">
						<div class="slider">
							<?php
								foreach ($headerSlidesList as $slideID) {
									$html = '';
									$html .= '<div class="item" id="item_' . $slideID . '">';
									$html .= $this->getLayout()->createBlock('cms/block')->setBlockId($slideID)->toHtml();
									$html .= '</div>';
									echo $html;
								}
							?>
						</div>
						<?php if($headerSliderConfig['slidertype'] == 0): ?>
						<div class="container_12">
						<?php endif; ?>
							<div class = 'next'><i class="fa fa-angle-right"></i></div>
							<div class = 'prev unselectable'><i class="fa fa-angle-left"></i></div>
						<?php if($headerSliderConfig['slidertype'] == 0): ?>
						</div>
						<?php endif; ?>
					</div>
				</div>
			</div>
			<?php if($headerSliderConfig['slidertype'] == 4): ?>
			</div>
		</div>
		<div class="grid_4 alpha omega right slider-banners">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($sliderBanners)->toHtml(); ?>
		</div>
	<?php endif; ?>
	<?php if($headerSliderConfig['slidertype'] == 3): ?>
			</div>
		</div>
	<?php endif; ?>
		<?php if($headerSliderConfig['slidertype'] == 2): ?>
			</div>
		</div>
		<div class="grid_3 alpha omega right slider-banners">
			<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($sliderBanners)->toHtml(); ?>
		</div>
	<?php endif; ?>
	<?php if($headerSliderConfig['slidertype'] == 1): ?>
			</div>
		</div>
	<?php endif; ?>
<?php if($headerSliderConfig['slidertype'] == 0): ?>
</div>
<?php endif; ?>
<script type="text/javascript">
	/* Slider Preloader */
	var sliderHolder = jQuery('.header-slider-holder');
	var sliderLoader = sliderHolder.find('.loader');
	
	var progress = 0;
	function animateFunc(){
		if(progress > 100){
			return false;
		}
		sliderLoader.html(progress+'%');
		progress+=5;
		setTimeout(animateFunc, 25);
	}
	setTimeout(animateFunc, 25);
	
	function loaded(){
		setTimeout(function(){
		
			img =  jQuery('.header-slider-container .iosSlider .slider .item img:first');
			height = img.height();
			if(img.parent('a').length){
				height = img.parent('a').outerHeight();
			}
		
			sliderLoader.html('');
			sliderLoader.fadeOut(1500, function(){
				jQuery(this).remove();
				sliderHolder.removeClass('loading').css('height', 'auto');
			});
			
			sliderHolder.animate({
			  height: height
			}, 500, "easeOutExpo");
			
		}, 1000);
	}
	
	jQuery(window).load(function(){
		slider_items_length = jQuery('.header-slider-container .iosSlider .slider .item').size();
		if(slider_items_length > 1){
			var slider_bullets = '<ul class="headerSliderSelectors">';
			for(i=1; i<=slider_items_length; i++){
				if(i==1){selected_item = ' selected'}else{selected_item = ''}
				slider_bullets += '<li class="button-item' + selected_item + '" id="item' + i + '">' + i + '</li>'
			}
			slider_bullets += '</ul>';
			<?php if($headerSliderConfig['slidertype'] != 0): ?>
				jQuery('.header-slider-container .iosSlider').append(slider_bullets);
			<?php else : ?>
				jQuery('.header-slider-container .iosSlider .slider + .container_12').append(slider_bullets);
			<?php endif; ?>
		}
  
	//Slider Container Ratio
		function sliderHeight(){
			setTimeout(function(){
				var slider_container = jQuery('.header-slider-container');
				var slider_img =  jQuery('.header-slider-container .iosSlider .slider .item img:first');
				var sliderHeight = slider_img.height();
				if(slider_img.parent('a')){
					sliderHeight = slider_img.parent('a').outerHeight();
				}
				slider_container.css({
					'padding-bottom': sliderHeight + 'px'
				});
				slider_container.find('.iosSlider').css({
					'height': sliderHeight + 'px'
				});
			}, 50);
		}
		sliderHeight();
		jQuery(window).resize(function(){sliderHeight();})
	
    jQuery('.header-slider-holder .iosSlider').iosSlider({
      responsiveSlideWidth: true,
      snapToChildren: true,
      desktopClickDrag: true,
      infiniteSlider: true,
      navSlideSelector: '.headerSliderSelectors .button-item',
      navNextSelector: '.header-slider-container .iosSlider .next',
      navPrevSelector: '.header-slider-container .iosSlider .prev',
      onSlideComplete: headerSlideComplete,
	  onSliderLoaded: headerSliderLoaded,
	  onSlideChange: headerSlideChange,
      <?php if(isset($headerSliderConfig ['autoSlide'])): ?>autoSlide: <?php echo $headerSliderConfig ['autoSlide']; ?><?php endif; ?>
      <?php if(isset($headerSliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $headerSliderConfig ['autoSlideTimer']; ?><?php endif; ?>
	  <?php if(isset($headerSliderConfig ['autoSlideTransTimer'])): ?>, autoSlideTransTimer: <?php echo $headerSliderConfig ['autoSlideTransTimer']; endif; ?>
	  <?php if(isset($headerSliderConfig ['desktopClickDrag'])): ?>, desktopClickDrag: <?php echo $headerSliderConfig ['desktopClickDrag']; endif; ?>
	  <?php if(isset($headerSliderConfig ['infiniteSlider'])): ?>, infiniteSlider: <?php echo $headerSliderConfig ['infiniteSlider']; endif; ?>
    });
	function headerSlideChange(args) {
		jQuery('.headerSliderSelectors .button-item').removeClass('selected');
		jQuery('.headerSliderSelectors .button-item:eq(' + (args.currentSlideNumber-1) + ')').addClass('selected');
	}
	
	function headerSlideComplete(args) {
			/* Slides Animation Presets */
			if(jQuery('.header-slider-container.boxed-slider').length){
			/* Boxed Slider */
				var slideTitle = [{left: '0', opacity: '1'}, 400]; // example: Animation settings: left = 50%, opacity = 100%;  Animation speed: 400ms
				var slideTitle2 = [{top: '0px', opacity: '1'}, 600];
				var slideText = [{right: '0', opacity: '1'}, 600];
				var slideList = [{left: '0', opacity: '1'}, 600];
				var slideImage = [{bottom: '0px', opacity: '1'}, 900];
				
			
			}else{
			/* Wide Slider */
				var slideTitle = [{left: '0', opacity: '1'}, 400];
				var slideTitle2 = [{top: '0px', opacity: '1'}, 600];
				var slideText = [{right: '0', opacity: '1'}, 600];
				var slideList = [{left: '0', opacity: '1'}, 600];
				var slideImage = [{bottom: '0px', opacity: '1'}, 900];
			}
			
			
			/* ============================================ */
			
			
			/* Animation Elements */
			/* ===slide title element=== */
			jQuery(args.sliderObject).find('h2').attr('style', '');
			jQuery(args.currentSlideObject).find('h2').animate(slideTitle[0], slideTitle[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide title 2 element=== */
			jQuery(args.sliderObject).find('h3').attr('style', '');
			jQuery(args.currentSlideObject).find('h3').animate(slideTitle2[0], slideTitle2[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide text element=== */
			jQuery(args.sliderObject).find('p').attr('style', '');
			jQuery(args.currentSlideObject).find('p').animate(slideText[0], slideText[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide list element=== */
			jQuery(args.sliderObject).find('ul').attr('style', '');
			jQuery(args.currentSlideObject).find('ul').animate(slideList[0], slideList[1], 'easeOutQuint');
			/* ========================== */
			
			/* ===slide button element=== */
			jQuery(args.sliderObject).find('h4').attr('style', '');
			jQuery(args.currentSlideObject).find('h4').animate(slideImage[0], slideImage[1], 'easeOutQuint');
			/* ========================== */
	  }
	
	function headerSliderLoaded(args) {
		headerSlideComplete(args);
		headerSlideChange(args);
		<?php if($headerSliderConfig['preloader'] == 1): ?>
			loaded();
		<?php endif; ?>
	}
	
    jQuery(window).on('orientationchange', function(e){
		setTimeout(function(){
			jQuery('.header-slider-holder .iosSlider').iosSlider('update');
		}, 500);
	});

  });
</script>
    <?php 
  endif;
endif;