<?php
$_product = $this->getProduct();
if($this->getLayout()->createBlock('cms/block')->setBlockId('unique_product_banner_'.$this->getProduct()->getId())->toHtml()){
	$product_banner_name = 'unique_product_banner_'.$this->getProduct()->getId();
}else{
	$product_banner_name = 'unique_product_banner';
}
echo '<div class="product-sibebar-banner">' . $this->getLayout()->createBlock('cms/block')->setBlockId($product_banner_name)->toHtml() . '</div>';