<?php
$installer = $this;
$installer->startSetup();
$installer->addAttributeGroup('catalog_product', 'Default', 'Meigee - Unique options', 9000);
$installer->addAttribute('catalog_product', 'unique_prsku', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product SKU',
    'note' => 'Will be displayed under product title',
    'source'            => 'ThemeOptionsUnique/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 1,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prlayout', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product Page Layout',
    'note' => 'Choose layout for product page',
    'source'            => 'ThemeOptionsUnique/attribute_source_productlayout',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 2,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prprevnext', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Prev and Next product buttons',
    'note' => 'Allows you to move between products within a category just in one click',
    'source'            => 'ThemeOptionsUnique/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 3,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prmoreviews', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'More views block',
    'note' => 'Slider option will work if product has 6+ related products',
    'source'            => 'ThemeOptionsUnique/attribute_source_slider',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 5,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prrelated', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Related products block',
    'note' => 'Slider option will work if product has more related products than can be displayed in one line',
    'source'            => 'ThemeOptionsUnique/attribute_source_slider',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 6,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_relatedpos', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Related products position',
    'note' => 'Choose position of this block',
    'source'            => 'ThemeOptionsUnique/attribute_source_relatedpos',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 6,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prcolleteral', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Collateral block',
    'note' => 'Choose how collateral prodcut will be displayed',
    'source'            => 'ThemeOptionsUnique/attribute_source_collateral',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 7,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prcolleteralpos', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Collateral block position',
    'note' => 'Choose position of this block',
    'source'            => 'ThemeOptionsUnique/attribute_source_collateralpos',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 8,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prcustom', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'textarea',
    'type'          => 'text',
    'label'         => 'Under product description',
    'note' => 'Replaces all static blocks set in product page options',
    'backend'       => '',
    'sort_order' => 9,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'wysiwyg_enabled' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_product', 'unique_prtabs', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'text',
    'type'          => 'text',
    'label'         => 'Products Tabs',
    'note'          => 'Comma separated list of static block identifiers. These static blocks will be displayed one below the other',
    'backend'       => '',
    'sort_order' => 10,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_product', 'unique_prrelatedcontent', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'textarea',
    'type'          => 'text',
    'label'         => '"Related" static block',
    'note' => 'Replaces all static blocks set in product page options',
    'backend'       => '',
    'sort_order' => 11,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'wysiwyg_enabled' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'        => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
));
$installer->addAttribute('catalog_product', 'unique_prbrand', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product Brand Image',
    'note' => 'Allows to display brand image on product pages',
    'source'            => 'ThemeOptionsUnique/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 12,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prbrandlink', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Link to brand search',
    'note' => 'Image will refer to search products by brand',
    'source'            => 'ThemeOptionsUnique/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 13,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prbrandtarget', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Link target blank',
    'note' => 'Choose "Enable" if you want open links in a new tab',
    'source'            => 'ThemeOptionsUnique/attribute_source_type',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 14,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'unique_prbrandpos', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Brand Image Position',
    'note' => 'Choose where your brand image will be shown',
    'source'            => 'ThemeOptionsUnique/attribute_source_brandpos',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 15,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));

$installer->addAttribute('catalog_product', 'unique_prsidebar', array(
    'group'         => 'Meigee - Unique options',
    'input'         => 'select',
    'type'          => 'int',
    'label'         => 'Product Page Sidebar',
    'note' => 'Choose if you want sidebar to be shown on a product page',
    'source'            => 'ThemeOptionsUnique/attribute_source_productsidebar',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 16,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->addAttribute('catalog_product', 'manufacturer_info', array(
    'group'         => 'General',
    'input'         => 'textarea',
    'type'          => 'text',
    'label'         => 'Manufacturer Info',
    'note' => 'Will be displayed with manufacturer image',
    'default' => 0,
    'default_value' => 0,
    'sort_order' => 99,
    'visible'       => 1,
    'required'      => 0,
    'user_defined' => 1,
    'searchable' => 0,
    'filterable' => 0,
    'comparable'    => 0,
    'visible_on_front' => 0,
    'visible_in_advanced_search'  => 0,
    'is_html_allowed_on_front' => 0,
    'global'     => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
));
$installer->endSetup();