<div class="comment-block">
	<div class="opc-block-title">
		<h3><?php echo $this->__('Comment')?></h3>
	</div>
	<form autocomplete="off">
	    <div class="discount">
	        <div class="discount-form">            
	            <div class="input-box">	                
	                <textarea class="input-text" id="customer_comment" name="customer_comment"></textarea>
	            </div>	            
	        </div>
	    </div>
	</form>
</div>