<?php
    $_productCollection = $this->getMyCollection();
    $category = $this->catName();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $this->productsAmount();
    $meigee_unique_general = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_general');
	$fancybox = $meigee_unique_general['fancybox'];
    $helpImg = $this->helper('ThemeOptionsUnique/images');
	$random = rand(5, 1500);
	$_addToCart = $this->addToCart();
	$_price = $this->productPrice();
	$_productName = $this->productName();
	$_quickView = $this->quickView();
	$wishlist = $this->wishlist();
	$randId = $this->getWidgetId();
	$compareproducts = $this->compareProducts();
	$ratingStars = $this->ratingStars();
	$ratingCustomerLink = $this->ratingCustLink();
	$ratingReviewLink = $this->ratingAddReviewLink();
?>
<?php // List Mode ?>
<ol class="products-list meigee-widget small">
    <?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php $_iterator=0; if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
			<div class="product-image">
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 800, null); ?><img <?php echo $helpImg->getImgSources($_product, 'small_image', 800, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
				<?php // Fancybox
				if ($fancybox['fancybox_status'] && $fancybox['fancybox_home'] == 1): ?>
					<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('fancybox'); ?></a>
				<?php endif; // End Fancybox ?>
			</div>
            <?php // Product description ?>
			<div class="product-shop">
				<?php if($_productName): ?>
					<h2 class="product-name">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
					</h2>
				<?php endif; ?>
				<?php $storeId = Mage::app()->getStore()->getId();
					$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
					if ($summaryData['rating_summary']): ?>
					<?php if ($ratingCustomerLink || $ratingReviewLink || $ratingStars) : ?>
						<div class="ratings">
							<?php if ($ratingStars) : ?>
								<div class="rating-box">
									<div class="rating" style="width: <?php echo $summaryData['rating_summary']; ?>%"></div> 
								</div>
							<?php endif; ?>
							<p class="rating-links">
								<?php if ($ratingCustomerLink) : ?>
									<a href="<?php echo $_product->getProductUrl() ?>#review-point"><?php echo $this->__('%d Review(s)', $summaryData['reviews_count']) ?></a>
								<?php endif; ?>
								<?php if ($ratingCustomerLink && $ratingReviewLink) : ?>
									<span class="separator">|</span>
								<?php endif; ?>
								<?php if ($ratingReviewLink) : ?>
									<a href="<?php echo $_product->getProductUrl() ?>#review-point"><?php echo $this->__('Add Your Review') ?></a>
								<?php endif; ?>
							</p>
						</div>
					<?php endif; ?>
				<?php endif; ?>
				<?php if($_price): ?>
					<?php echo $this->getPriceHtml($_product, true) ?>
				<?php endif; ?>
				<div class="list-small-buttons">
					<?php if($_product->isSaleable() and $_addToCart): ?>
						<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
							<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped() || $_product->isConfigurable()) ): ?>
								<div class="button-holder homecart">
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" data-style="fill" data-vertical onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId().$random; ?>')"><span><span><i class="fa fa-shopping-cart"></i></span></span></button>
								</div>
							<?php else: ?>
								<div class="button-holder homecart">
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><i class="fa fa-shopping-cart"></i><span><i class="fa fa-shopping-cart"></i></span></span></button>
									<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
								</div>
							<?php endif; ?>
						<?php }else{ ?>
							 <div class="button-holder homecart"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><span><i class="fa fa-shopping-cart"></i></span></span></button></div>
						<?php } ?>
					<?php endif; ?>
					<?php if ($wishlist || $compareproducts) : ?>
						<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
									<li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId().$random; ?>");return false;' class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('wishlist'); ?><span id='ajax_wishlist_loading<?php echo $_product->getId().$random; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
									<li><a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId().$random; ?>");return false;' class="link-compare"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('compare'); ?><span id='ajax_loading<?php echo $_product->getId().$random; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span></a></li>
								<?php endif; ?>
							</ul>
						<?php }else{?>
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
									<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('wishlist'); ?></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
									<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('compare'); ?></a></li>
								<?php endif; ?>
								</ul>
						<?php } ?>
					<?php endif; ?>
					<?php if(Mage::getStoreConfig('ajax/general/enabledpro') and $_quickView){ ?>
						<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId().$randId; ?>')"><span><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('quickview'); ?></span></button>
						<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox-list-small' id='fancybox<?php echo $_product->getId().$randId; ?>' style='display:none'>Test</a>
					<?php } ?>
				</div>
			</div>
        </li>
    <?php if (++$i == $_collectionSize ) break; endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('.ajax-fancybox-list-small').fancybox(
				{
				   hideOnContentClick : true,
				   width:600,
				   autoDimensions: true,
				   type : 'iframe',
				   showTitle: false,
				   scrolling: 'no',
				   onComplete: function(){
					jQuery('#fancybox-frame').load(function() { // wait for frame to load and then gets it's height
						jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
						jQuery.fancybox.resize();
					 });

				   }
				}
			);
		});
		function showOptions(id){
			jQuery('#fancybox'+id).trigger('click');
		}
		function setAjaxData(data,iframe){
			if(data.status == 'ERROR'){
				alert(data.message);
			}else{
				if(jQuery('.top-cart')){
					jQuery('.top-cart').replaceWith(data.sidebar);
				}
				jQuery.fancybox.close();
				//jQuery('body').append('<div class="add-to-cart-success">test3' + data.message +' <br /><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Go to Shopping Cart') ?></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
				
				//Added by Ankit
				jQuery('body').append('<div style="display: block;height:'+jQuery(window).height()+';" class="ajax-box-overlay-layered"></div>');
				jQuery('body').append('<div class="add-to-cart-success .custom-add-to-cart-success"> <div class="add-to-cart-header"><h2 class="add-to-cart-h2">ITEM ADDED TO CART</h2></div><div class="add-to-cart-data-msg">' + data.message +'  <br /><br /> <a class="add-to-cart-custom-buttoncontinue" href="#" >CONTINUE SHOPPING</a>&nbsp;&nbsp;<a class="add-to-cart-custom-button" href="<?php echo $this->getUrl('checkout/cart'); ?>">VIEW CART</a></div></div>');
				
				//Commented by Ankit
				/*setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);*/
				
				jQuery('.add-to-cart-custom-buttoncontinue').click(function(){
					jQuery('.add-to-cart-success').slideUp(500)
					jQuery('.ajax-box-overlay-layered').hide();	
					return false;
				});
				
				jQuery('.add-to-cart-success a.btn-remove').click(function(){
					jQuery(this).parent().slideUp(500);
					return false;
				});
			}
		}
		function setLocationAjax(url,id){
			url += 'isAjax/1';
			url = url.replace("checkout/cart","ajax/index");
			try {
				jQuery.ajax( {
					url : url,
					dataType : 'json',
					success : function(data) {
						setAjaxData(data,false);
					}
				});
			} catch (e) {
			}
		}
	</script>
