<?php
    $_productCollection = $this->getMyCollection();
	//$gridMode = $this->sliderGridSelection();
	$visibleProducts = $this->getData('visible_products');
	$productCount = count($_productCollection);
	if (count($_productCollection)) {
		$category = $this->catName();
		$_helper = $this->helper('catalog/output');
		$_collectionSize = $this->productsAmount();
		$random = rand(5, 1500);
		$_addToCart = $this->addToCart();
		$_price = $this->productPrice();
		$_productName = $this->productName();
		$_quickView = $this->quickView();
		$_quickViewPos = $this->getQuickViewPos('quickview_position_slider');
		$wishlist = $this->wishlist();
		$compareproducts = $this->compareProducts();
		$ratingStars = $this->ratingStars();
		$ratingCustomerLink = $this->ratingCustLink();
		$ratingReviewLink = $this->ratingAddReviewLink();
		$buttonsPosition = $this->getButtonsPosition();
		$randId = $this->getWidgetId();
		$meigee_unique_general = MAGE::helper('ThemeOptionsUnique')->getThemeOptionsUnique('meigee_unique_general');
		$fancybox = $meigee_unique_general['fancybox'];
		$helpImg = $this->helper('ThemeOptionsUnique/images');
		$labelsoptions = $meigee_unique_general['productlabels'];
		$productOnlyXleft = $meigee_unique_general['productlabels']['labelonlyxleft'];
		$labelsType = $meigee_unique_general['productlabels']['labelview'];
		switch ($visibleProducts) {
			case 2:
				$visibleProducts = 'two-products';
			break;
			case 3:
				$visibleProducts = 'three-products';
			break;
			case 4:
				$visibleProducts = 'four-products';
			break;
			case 5:
				$visibleProducts = 'five-products';
			break;
			case 6:
				$visibleProducts = 'six-products';
			break;
			case 7:
				$visibleProducts = 'seven-products';
			break;
			case 8:
				$visibleProducts = 'eight-products';
			break;
		}
		switch ($visibleProducts) {
			case 'two-products':
				$imgSize = 814;
			break;
			case 'three-products':
				$imgSize = 543;
			break;
			case 'four-products':
				$imgSize = 424;
			break;
			case 'five-products':
				$imgSize = 325;
			break;
			case 'six-products':
				$imgSize = 271;
			break;
			case 'seven-products':
				$imgSize = 233;
			break;
			case 'eight-products':
				$imgSize = 203;
			break;
		}
?>
<?php // Slider ?>
<div class="slider-container widget-container">
	<?php if($productCount > $visibleProducts): ?>
		<div class="home-container">
			<div class="home-slider-conainer">
				<div class="home-slider es-carousel-wrapper" id="home-slider-<?php echo $randId; ?>">
					<div class="widget-slider <?php echo $visibleProducts; ?>">
						<ul class="products-grid<?php echo ' '.$labelsType; ?> carousel-ul">
							<?php $i=0; foreach ($_productCollection as $_product): ?>
							<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
							<li class="item<?php if($labelsoptions['labelsorder'] == 'sale_new'):?> labels-sale-new<?php endif; ?>">
								<div class="indent">
									<div class="product-img-box">
										<?php echo MAGE::helper('ThemeOptionsUnique')->getProductLabels($_product, 'new'); ?>
										<?php if($productOnlyXleft and MAGE::helper('ThemeOptionsUnique')->getProductOnlyXleft($_product)): ?>
											<?php echo MAGE::helper('ThemeOptionsUnique')->getProductOnlyXleft($_product); ?>
										<?php else: ?>
											<?php echo MAGE::helper('ThemeOptionsUnique')->getProductLabels($_product, 'sale'); ?>
										<?php endif; ?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', $imgSize, null); ?><img <?php echo $helpImg->getImgSources($_product, 'small_image', $imgSize, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
										<?php  // Fancybox
										if ($fancybox['fancybox_status'] && $fancybox['fancybox_home'] == 1 and $_quickViewPos == 0): ?>
												<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('fancybox'); ?></a>
											<?php endif; 
										// End Fancybox ?>
										<?php if ($_quickView and $_quickViewPos ==1) : ?>
											<div class="quick-view-wrapper">
												<?php if ($fancybox['fancybox_status'] && $fancybox['fancybox_home'] == 1 and $_quickViewPos == 1): ?>
													<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('fancybox'); ?></a>
												<?php endif; ?>
												<?php if (Mage::getStoreConfig('ajax/general/enabledpro') and $_quickView == 1) : ?>
														<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId().$randId; ?>')"><span><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('quickview'); ?><span><?php echo $this->__('Quick View') ?></span></span></button>
														<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox-grid' id='fancybox<?php echo $_product->getId().$randId; ?>' style='display:none'>Test</a>
												<?php endif; ?>
											</div>
										<?php endif; ?>
									</div>
									<?php if($_productName): ?>
										<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
									<?php endif; ?>
									<?php $storeId = Mage::app()->getStore()->getId();
										$summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
										if ($summaryData['rating_summary']): ?>
										<?php if ($ratingCustomerLink || $ratingReviewLink || $ratingStars) : ?>
											<div class="ratings">
												<?php if ($ratingStars) : ?>
													<div class="rating-box">
														<div class="rating" style="width: <?php echo $summaryData['rating_summary']; ?>%"></div> 
													</div>
												<?php endif; ?>
												<p class="rating-links">
													<?php if ($ratingCustomerLink) : ?>
														<a href="<?php echo $_product->getProductUrl() ?>#review-point"><?php echo $this->__('%d Review(s)', $summaryData['reviews_count']) ?></a>
													<?php endif; ?>
													<?php if ($ratingCustomerLink && $ratingReviewLink) : ?>
														<span class="separator">|</span>
													<?php endif; ?>
													<?php if ($ratingReviewLink) : ?>
														<a href="<?php echo $_product->getProductUrl() ?>#review-point"><?php echo $this->__('Add Your Review') ?></a>
													<?php endif; ?>
												</p>
											</div>
										<?php endif; ?>
									<?php endif; ?>
									<?php if($_price): ?>
										<?php echo $this->getPriceHtml($_product, true) ?>
									<?php endif; ?>
									<?php if($_product->isSaleable() and $_addToCart): ?>
										<?php if(Mage::getStoreConfig('ajax/general/enabledpro')){ ?>
											<?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped() || $_product->isConfigurable()) ): ?>
												<div class="button-holder">
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" data-style="fill" data-vertical class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId().$random; ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
													<span id='ajax_loader<?php echo $_product->getId().$random; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span>
												</div>
											<?php else: ?>
												<div class="button-holder">
													<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button" onclick="showOptions('<?php echo $_product->getId()?>')"><span><i class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button>
													<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Test</a>
												</div>
											<?php endif; ?>
										<?php }else{ ?>
											<div class="button-holder"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><i class="fa fa-shopping-cart"></i><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
										<?php } ?>
									<?php endif; ?>
									<?php if ($wishlist || $compareproducts || $_quickView) : ?>
										<div class="slider-buttons">
											<?php if(Mage::getStoreConfig('ajax/wishlistcompare/enabledpro')){?>
												<ul class="add-to-links">
													<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
														<li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId().$random; ?>");return false;' class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('wishlist'); ?><span id='ajax_wishlist_loading<?php echo $_product->getId().$random; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span></a></li>
													<?php endif; ?>
													<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
														<li><a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId().$random; ?>");return false;' class="link-compare"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('compare'); ?><span id='ajax_loading<?php echo $_product->getId().$random; ?>' class="ajax-loader-item" style='display:none'><img src='<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>' alt="" /></span></a></li>
													<?php endif; ?>
												</ul>
											<?php }else{?>
												<ul class="add-to-links">
													<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
														<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('wishlist'); ?></a></li>
													<?php endif; ?>
													<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
														<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('compare'); ?></a></li>
													<?php endif; ?>
													</ul>
											<?php } ?>
											<?php if(Mage::getStoreConfig('ajax/general/enabledpro') and $_quickViewPos == 0){ ?>
												<button type="button" title="<?php echo $this->__('Quick View') ?>" class="button btn-quick-view" onclick="showOptions('<?php echo $_product->getId().$randId; ?>')"><span><?php echo MAGE::helper('ThemeOptionsUnique')->getIcon('quickview'); ?><span><?php echo $this->__('Quick View') ?></span></span></button>
												<a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='ajax-fancybox-slider' id='fancybox<?php echo $_product->getId().$randId; ?>' style='display:none'>Test</a>
											<?php } ?>
										</div>
									<?php endif; ?>
								</div>
							</li>
							<?php if (++$i > $_collectionSize-1 ) break; endforeach ?>
						</ul>
					</div>
					<?php if($buttonsPosition == 1): ?>
						<div class="widget-slider-buttons">
					<?php endif; ?>
						<div class = 'next'><i class="fa fa-angle-right"></i></div>
						<div class = 'prev unselectable'><i class="fa fa-angle-left"></i></div>
					<?php if($buttonsPosition == 1): ?>
						</div>
					<?php endif; ?>
				</div>
			</div>
		</div>
		<div class="clear"></div>
		<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		<script type="text/javascript">
		if(!jQuery('body').hasClass('mobile-device')){
				setTimeout(function(){
					function widthCorrector(){
							var widget = jQuery('#home-slider-<?php echo $randId; ?>');
							widget.children('style').remove();
							var widgetWidth = widget.width();
							widget.find('.widget-slider li.item:first').attr('style', '');
							var widgetItemWidth = widget.find('.widget-slider li.item:first').width();
							setTimeout(function(){
								var columnsCount = Math.round(widgetWidth/widgetItemWidth);
								var columnWidth = Math.floor(widgetWidth/columnsCount);
								var widgetItemsCss = '<style type="text/css">#home-slider-<?php echo $randId; ?> .widget-slider li.item{width:'+ columnWidth +'px;}</style>';
								widget.append(widgetItemsCss);
							}, 200);
					}
					widthCorrector();
					jQuery(window).resize(function(){widthCorrector()});
				}, 150);
			}
		jQuery(window).load(function(){
			/* slides width corrector */
			
		
			jQuery('#home-slider-<?php echo $randId; ?> .widget-slider').iosSlider({
			  responsiveSlideWidth: true,
			  snapToChildren: true,
			  desktopClickDrag: true,
			  infiniteSlider: false
			  <?php echo $this->getSliderOptions(); ?>,
			  /* navSlideSelector: '.sliderNavi .naviItem', */
			  navNextSelector: '#home-slider-<?php echo $randId; ?> .next',
			  navPrevSelector: '#home-slider-<?php echo $randId; ?> .prev'
			  <?php if(isset($sliderConfig ['autoSlide'])): ?>, autoSlide: <?php echo $sliderConfig ['autoSlide']; ?><?php endif; ?>
			  <?php if(isset($sliderConfig ['autoSlideTimer'])): ?>, autoSlideTimer: <?php echo $sliderConfig ['autoSlideTimer']; ?><?php endif; ?>
			});
			function widget_slider_height_<?php echo $randId; ?>(){
				setTimeout(function(){
					var widget_slider_height = 0;
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .products-grid li.item').each(function(){
						if(jQuery(this).height() > widget_slider_height){
							widget_slider_height = jQuery(this).height();
						}
					})
					jQuery('.widget-container #home-slider-<?php echo $randId; ?> .widget-slider').css({
						'min-height': (widget_slider_height+2),
						'height': 'auto'
					});
					
				}, 1000);
			}
			widget_slider_height_<?php echo $randId; ?>();
			function sliderButtonsPosition_<?php echo $randId; ?>() {
				if(jQuery('#home-slider-<?php echo $randId; ?> .widget-slider-buttons').length){
					var maxHeight = 0;
					jQuery('#home-slider-<?php echo $randId; ?> li.item .product-image img').each(function() {
						if (jQuery(this).height() > maxHeight){
							maxHeight = jQuery(this).height();
						}
						jQuery('#home-slider-<?php echo $randId; ?> .next, #home-slider-<?php echo $randId; ?> .prev').css('top', (maxHeight/2));
					});
				}
			}
			sliderButtonsPosition_<?php echo $randId; ?>();
			jQuery(window).resize(function(){widget_slider_height_<?php echo $randId; ?>(); sliderButtonsPosition_<?php echo $randId; ?>();});
		  });
		  jQuery(document).ready(function(){
				jQuery('.widget-container').each(function(){
					if(!jQuery(this).prev().hasClass('page-title')){
						jQuery(this).addClass('no-title');
					}
				});
				jQuery('.ajax-fancybox-slider').fancybox(
					{
					   hideOnContentClick : true,
					   width:600,
					   autoDimensions: true,
					   type : 'iframe',
					   showTitle: false,
					   scrolling: 'no',
					   afterLoad: function(){
							setTimeout(function(){
								var frameBodyHeight = jQuery('.fancybox-iframe').contents().find('body').height();
								if(jQuery(window).height() > frameBodyHeight+30){
									jQuery('.fancybox-inner').css('height', frameBodyHeight);
								}
							}, 1000);
						}
					}
				);
			});
			function showOptions(id){
				jQuery('#fancybox'+id).trigger('click');
			}
			function setAjaxData(data,iframe){
				if(data.status == 'ERROR'){
					alert(data.message);
				}else{
					if(jQuery('.top-cart')){
						jQuery('.top-cart').replaceWith(data.sidebar);
					}
					jQuery.fancybox.close();
					jQuery('body').append('<div class="add-to-cart-success">test6' + data.message +' <br /><a href="<?php echo $this->getUrl('checkout/cart'); ?>"><?php echo $this->__('Go to Shopping Cart') ?></a><a href="#" class="btn-remove"><i class="fa fa-times"></i></a></div>');
					setTimeout(function () {jQuery('.add-to-cart-success').slideUp(500)}, 5000);
					jQuery('.add-to-cart-success a.btn-remove').click(function(){
						jQuery(this).parent().slideUp(500);
						return false;
					});
				}
			}
			function setLocationAjax(url,id){
				url += 'isAjax/1';
				url = url.replace("checkout/cart","ajax/index");
				jQuery('#ajax_loader'+id).show();
				try {
					jQuery.ajax( {
						url : url,
						dataType : 'json',
						success : function(data) {
							jQuery('#ajax_loader'+id).hide();
							setAjaxData(data,false);
						}
					});
				} catch (e) {
				}
			}
		</script>
	<?php else: ?>
		<div class="no-widget"><?php echo $this->__("Warning: Please make sure you have %s+ products to display in the slider, otherwise widget won't be displayed", $visibleProducts+1) ?></div>
	<?php endif; ?>
</div>
<?php 
	unset ($randId);
}
?>
