<div class="fullwidthbanner-container">
<div class="fullwidthbanner">
 <ul>
<li data-transition="random" data-slotamount="7" data-link="http://www.google.de" class="slide1"><img src="<?php echo $this->getSkinUrl('images/banners/main-banner1.jpg') ?>" alt="" />
<div class="slide1_img tp-caption start" data-x="500" data-y="130" data-speed="700" data-start="800" data-easing="easeOutBounce">
<img src="<?php echo $this->getSkinUrl('images/banners/main-banner1-img.png') ?>" alt="" />
</div>
<div class="caption1 tp-caption  skewfromright" data-x="940" data-y="230" data-speed="700" data-start="1200" data-easing="easeInExpo">SHOES</div>
<div class="caption2 tp-caption  skewfrombottom" data-x="810" data-y="270" data-speed="900" data-start="1500" data-easing="easeOutQuint">STARTING FROM $256.00</div>
<div class="caption3 tp-caption  skewfromleft" data-x="50" data-y="130" data-speed="900" data-start="1400" data-easing="easeInOutCubic">QUALITY  WITHOUT  COMPROMISE</div>
<div class="caption4 tp-caption  skewfromleftshort customout" data-x="50" data-y="180" data-speed="500" data-start="1800" data-easing="easeOutBack"><b>BIG SALE</b> UP TO 25% OFF</div>
<div class="caption sfb medium_grey" data-x="50" data-y="230" data-speed="700" data-start="2500">SHOP NOW</div>
</li>
<li data-transition="random" data-slotamount="7" data-link="http://www.google.de" class="slide2"><img src="<?php echo $this->getSkinUrl('images/banners/main-banner2.png') ?>" alt=""/> 
<div class="slide2_img tp-caption sfb start" data-x="600" data-y="80" data-speed="700" data-start="800" data-easing="easeOutBack">
<img src="<?php echo $this->getSkinUrl('images/banners/main-banner2-img.png') ?>" alt="" />
</div>
<div class="caption5 tp-caption sft" data-x="150" data-y="130" data-speed="900" data-start="1400" data-easing="easeOutBack">
<img src="<?php echo $this->getSkinUrl('images/banners/main-banner2-txt.png') ?>" alt="" />
</div>
<div class="caption6 tp-caption  skewfromleftshort customout" data-x="150" data-y="215" data-speed="500" data-start="1800" data-easing="easeOutBack"><span>BIG SALE</span></br>UP TO 70% OFF SALE
</div>
<div class="caption sfb medium_grey" data-x="150" data-y="300" data-speed="700" data-start="2500">SHOP NOW</div>
</li>
<li data-transition="random" data-slotamount="7" data-link="http://www.google.de" class="slide2"><img src="<?php echo $this->getSkinUrl('images/banners/main-banner3.jpg') ?>" alt="" />
<div class="caption7 tp-caption  sft" data-x="180" data-y="170" data-speed="900" data-start="1400" data-easing="easeOutQuad">I feel so great with Look</div>
<div class="caption8 tp-caption  lfl tp-resizeme start" data-x="240" data-y="220" data-speed="500" data-start="2200" data-easing="easeInQuart">2O% OFF ALL FASHION ACCESSORIES</div>
<div class="caption sfb medium_grey" data-x="350" data-y="260" data-speed="700" data-start="2500">SHOP NOW</div>
</li>
</ul>
</div>
</div>